name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python

      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependecies
      run: |
        echo ">>> Check Python version"
        python3 -c "import sys; print(f'Python version: {sys.version}')"
        echo ">>> Download and install Poetry"
        curl -sSL https://install.python-poetry.org | python3 -
        echo ">>> Check Poetry version"
        poetry --version
        echo ">>> Create Poetry virtualenv"
        poetry env use python3
        echo ">>> Create Poetry lock file from pyproject.toml"
        poetry lock
        poetry add pylint
        echo ">>> Install required modules"
        poetry install
        echo ">>> List installed modules"
        poetry show

    - name: Use pylint to check python code
      run: |
        source $(poetry env info --path)/bin/activate
        python3 -m pylint $(git ls-files '*.py') --rcfile=.pylintrc
