# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Application test

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
    
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
        
    - name: Install dependecies
      run: |
        echo ">>> Check Python version"
        python3 -c "import sys; print(f'Python version: {sys.version}')"
        echo ">>> Download and install Poetry"
        curl -sSL https://install.python-poetry.org | python3 -
        echo ">>> Check Poetry version"
        poetry --version
        echo ">>> Create Poetry virtualenv"
        poetry env use python3
        echo ">>> Create Poetry lock file from pyproject.toml"
        poetry lock
        echo ">>> Install required modules"
        poetry install
        echo ">>> List installed modules"
        poetry show

    - name: Test with pytest
      run: |
        source $(poetry env info --path)/bin/activate
        python3 -m pytest tests/
        
