# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Application test

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
    
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
        
    - name: Install dependecies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version
        pwd
        ls
        
